CREATE TABLE `post` (
	`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` varchar(255) DEFAULT NULL,
	`body` text DEFAULT NULL,
	`created` int(10) UNSIGNED DEFAULT NULL,
	`updated` int(10) UNSIGNED DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin COMMENT='';

CREATE TABLE `comment` (
	`id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`post_id` int(10) UNSIGNED NOT NULL,
	`content` text DEFAULT NULL,
	`created` int(10) UNSIGNED DEFAULT NULL,
	`updated` int(10) UNSIGNED DEFAULT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`post_id`) REFERENCES `blog`.`post` (`id`)   ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=`InnoDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin COMMENT='';
